version: "3.8"


services:

  node_build:
    container_name: node_build
    image: "node:14"
    working_dir: /home/node/app
    volumes:
      - /home/ubuntu/iot-project/app/:/home/node/app


    command: sh -c "npm run build"